columns:
  - Transaction Type
  - Channel
  - Is 3DS
  - Is Token
  - Is Disputable?
  - Decision
  - Decline Reason Code
  - Issuer Name
  - Issuer Country
  - Issuer Region
  - Funding source
  - Acquirer Name
  - Acquirer Country
  - Acquirer Region
  - Jurisdiction
  - Is Disputed?
  - Is Fraud?
  - Dispute Type
  - Amount

groups:
  issuer:
    title: Which issuer has problems?
    info: |
      Move the slider to see where the most fraud happens across issuers, regions *and* countries.

      By "most fraud", we mean high fraud rates combined with high volumes. This is:

      - [Wells Fargo USA](#1) has the highest overall fraud level
      - [JP Morgan USA](#4) is the next biggest problem area
      - [Credit (not debit)](#7) is specifically the issue for Wells Fargo USA
      - [Bank of America USA](#8) is the next biggest problem area
      - [Debug (not credit)](#11) is JP Morgan's bigger problem (but [credit is close](#12))
      - [Barclays UK](#14) is the next biggest problem area
      - [Nordea Ireland's debug](#17) follows
    groups: [Issuer Name, Issuer Region, Issuer Country, Funding source]
    start: 1
  # acquirer:
  #   title: Which acquirer has problems?
  #   info: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  #   groups: [Acquirer Name, Acquirer Region, Acquirer Country, Funding source]
  #   start: 5
  issuer-acquired:
    title: Which issuer-acquirer mix has problems?
    info: |
      Let's dig deeper. Do problems increase for issuers with specific acquirers? Or vice versa?

      - [Banco Bradesco's debit cards acquired by FNB Omaha](#1) have a surprisingly high fraud rate
      - [TSB Bank credit cards with PKO Bank](#2) is another example
      - [Bank of New Zealand credit cards with IndusInd Bank](#3) is yet another problem area
    groups: [Issuer Name, Acquirer Name, Funding source]
    showKey: true
    leaf: true
    start: 1
  transaction:
    title: Which transactions have problems?
    info: |
      We can dig deeper with any set of combinations. This tree explores the combinations of:

      - Decline Reason Code
      - Transaction Type
      - Channel
      - Is 3DS
      - Is Disputable?

      Play around and see what you find!

    groups:
      - Decline Reason Code
      - Transaction Type
      - Channel
      - Is 3DS
      - Is Disputable?
    showKey: true
    start: 1

metrics:
  - Is Disputed?
  - Is Fraud?
  - Amount
  - Count
